create table if not exists public.despite_leads (
  id bigint generated by default as identity primary key,
  email text unique not null,
  source text default 'landing_page',
  user_agent text,
  created_at timestamptz default now()
);

create index if not exists despite_leads_email_idx
on public.despite_leads (email);

create index if not exists despite_leads_created_at_idx
on public.despite_leads (created_at desc);

alter table public.despite_leads enable row level security;

drop policy if exists "Allow public waitlist inserts"
on public.despite_leads;

create policy "Allow public waitlist inserts"
on public.despite_leads
for insert
to anon, authenticated
with check (true);